### ISSUE TITLE
Bad JSON when posts don't have a featured image

### ISSUE THREAD

**Issue by svrooij** [BraadMartin/better-rest-api-featured-images#1]
First off all I want to say your plugin is really useful!!

But there seems to be a problem with the JSON when a post doesn't have a post image.
It responds with `better_featured_image = 0` but it should either not be present or be `null`

Some parses die with this.

**Comment by BraadMartin** [comment]
Hello @svrooij,

I'm glad that you are finding the plugin useful. The reason it returns 0 when no featured image has been set is because this is the value that the core `featured_image` field returns when no featured image has been set. I wanted to match core behavior as much as possible.

If the core REST API ever changes this behavior, I'm happy to update this plugin to match. There is some interesting history in the issues on the WP-API Github repo that explain how they ended up with the current behavior.

I'm interested in hearing more about how passing the 0 can break parsers though. If that is an issue I'd be happy to add a filter to let you specify a value to return on posts without a featured image.

**Comment by svrooij** [comment]
By default the featured_image returns an integer. So it makes sense to return a 0 if not present. (Although skipping it would make even more sense)

But the better_featured_image returns an object. So if that object is not present it makes sense to skip it or return null.

The default C# parser (Newtonsoft.Json) doesn't like this behavior. It expects a class but gets an integer. So it will give an deserialization error.

And one other thing, JSON was designed to be small, so it make more sense to skip a property that isn't present then to add a value that cannot Ben deserialized into the expected property.

**Comment by BraadMartin** [comment]
Ah, I see what you're saying. Thanks for providing that information. I'll update the plugin to return null when the post doesn't have a featured image.

**Comment by BraadMartin** [comment]
Alright, just pushed version 1.0.1 to the plugins repo, now it returns `null` instead of `0` on posts without a featured image.

Let me know if there are any other issues, and thanks again for using!
