### ISSUE TITLE
No Better Featured Image Field in Custom Post-types (Pods)

### ISSUE THREAD

**Issue by belafonte** [BraadMartin/better-rest-api-featured-images#8]
Hello,

the better featured image field is missing when using the plugin together with custom post types (in this case Pods). 
Changing line 32 to:
add_action( 'rest_api_init', 'better_rest_api_featured_images_init');

and adding:
'update_callback' => null, 

after line 58 as well as 67, solves the issue.

Is there any reason you used 'init' instead of  'rest_api_init' and left out those lines?

Cheers
bel

**Comment by BraadMartin** [comment]
Hello Belafonte,

The issue you raised just sent me on a long chase through Pods. It turns out that Pods registers REST API support on `init` at priority 12, which is exactly when my plugin registers its field, so there is a conflict. If I change my plugin to use `init` at priority 13, or if I switch to `rest_api_init` as you suggest, the `better_featured_image` field comes through and everything works fine.

However, I can't change the hook or priority that my plugin initializes on without potentially breaking backwards compatibility. If anyone using my plugin has unhooked and rehooked the initialization of my plugin to a new hook or priority then me changing this in my plugin would cause their code to stop working as it did before.

You're in luck though, because the WordPress hook system already gives you a way to move the initialization of my plugin to any hook and priority that you want. Simply unhook my function from `init` at priority 12 and rehook it wherever you want:

```
add_action( 'plugins_loaded', function() {
    remove_action( 'init', 'better_rest_api_featured_images_init', 12 );
    add_action( 'init', 'better_rest_api_featured_images_init', 13 );
});
```

^That would move it to `init` and priority 13, or you could move it to `rest_api_init` instead:

```
add_action( 'plugins_loaded', function() {
    remove_action( 'init', 'better_rest_api_featured_images_init', 12 );
    add_action( 'rest_api_init', 'better_rest_api_featured_images_init' );
});
```

Both of these examples work for me using Pods.

To your other suggestion about adding an `update_callback`, I'm open to this but I don't think it's necessary. The default value for `update_callback` already gets set to `null`, as you can see on line 246 of the file plugin.php in the REST API plugin, where `register_rest_field()` gets defined (which my plugin uses):

```
    function register_rest_field( $object_type, $attribute, $args = array() ) {
        $defaults = array(
            'get_callback'    => null,
            'update_callback' => null,
            'schema'          => null,
        );

        $args = wp_parse_args( $args, $defaults );
        ...
```

To your question about why `init` over `rest_api_init`, when I wrote this plugin originally I was on the fence about this. My thinking at the time was that you might want to know what custom fields you have registered to show in the REST API during a normal non-REST API request, such as in the admin. Let's say for example you want to have an admin page that lists which custom fields are visible in the REST API. Since `rest_api_init` only fires while serving an actual REST API request (it doesn't fire when serving a regular admin request) if I registered my field on that hook then the fact that the field was registered wouldn't be visible to other code unless a REST API request was being served.

If you have a site that only interacts with WP over the API then hooking on `rest_api_init` would be more appropriate, and you're welcome to make the switch using the code snippet I pasted above. If I was writing the plugin today I probably would hook on `rest_api_init`, but since I can't safely change it now without potential backwards compatibility issues, I'm going to keep it as is.

Thanks for opening an issue about this though. Hopefully if anyone else runs into the same issue they will find this thread and be able to implement one of the fixes I've shared here.

**Comment by belafonte** [comment]
Wow what a detailed answer of you. Thanks a lot for the insights into Wordpress and your decisions. Seems absolutely legit to not switch to "rest-api-init" by now. Yeah hopefully somebody else who runs into the issue finds this thread. Spent a day on figuring out what was causing the error. Especially mean because it was working sometimes and stopping working again and i never really used Wordpress as a backend before so i was completely lost in the first case.

Cheers and thanks again
bel
